config/routes.rb
Rails.application.routes.draw do
  root :to => "notes#new"
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note
  include Mongoid::Document
  field :title, type: String
  field :content, type: String
  field :tag, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content, :tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
    <%= stylesheet_link_tag href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="margin-top: 30px">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="form-group">
      <%= form.label :tag  %>
      <%= form.text_field :tag %>
    </div>

    <div class="row">
      <input type="submit" name="commit" value="Save" class="btn btn-success" style="margin-top: 20px;margin-left: 50px; ">
    </div>
    <div class ="row">
    <%= link_to 'Go Back', notes_path, :class=>"back-button" %> 
    <% if !note.new_record?.present? %>
      <%= link_to 'Show', @note, :class=>"back-button" %> 
    <% end %>
  </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="container" style="text-align:left"> <h1 style="font-size: 2.0rem;margin-top: 40px">Create New </h1> </div>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>
<% if @notes.present? %>
  <h1 class="text-center" style="font-size:2.0rem">Notes</h1>
  <div class="container" style="margin-top:30px">
    <div class="row">
    <table class ="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>Tag</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @notes.each do |note| %>
          <tr>
              <td><%= note.title %></td>
              <td><%= note.content %></td>
              <td><%= note.tag %></td>
                <td><%= link_to 'Show', note , :class=>'btn btn-success btn-sm' %>
                <%= link_to 'Edit', edit_note_path(note) , :class => "btn btn-success btn-sm"  %>
                <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>
<% else  %>
  <p style="text-align: center;"> No notes to display </p>
<%end %>
<br>
<div class="container" align="text-center">
<%= link_to 'New Note', new_note_path, :class => 'btn btn-info' %>
</div>

app/views/notes/new.html.erb
<div class="container" style="text-align:left"> <h1 style="font-size: 2.0rem;margin-top: 40px">Create New </h1> </div>

<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="content" style="margin-top: 30px;margin-left: 10px">

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @note.tag %>
</p>
</div>
<div class="content" style="margin-left: 10px">
<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>
</div>